version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=3000
        - NODE_ENV=production
    ports:
      - "5918:3000" # Map container port 3000 to host port 3000
    env_file:
      - .env.local
    volumes:
      # Mount a named volume to a directory where the database file will be stored.
      - "cofi_data:/app/data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/api/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    # Resource limits for better container orchestration
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  cofi_data:
    driver: local
